### ISSUE TITLE
[PE-D][Tester E] Long tag names overflow out of UI

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-3/tp#190]
![image.png](https://raw.githubusercontent.com/xqtann/ped/main/files/fc601a53-191c-4799-9055-99deb0a1efa1.png)

Good to have limit to tag length, so that it will not overflow out of the box in UI.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: xqtann/ped#2

**Comment by YangQF2002** [comment]
Fixed in #155
