### ISSUE TITLE
[PE-D][Tester E] Incorrect error message displayed

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F09-3/tp#207]
![image.png](https://raw.githubusercontent.com/xqtann/ped/main/files/2065b174-0fbd-457c-9836-497af793af76.png)

Error message should be same as when input is `delete_vendor 88`

![image.png](https://raw.githubusercontent.com/xqtann/ped/main/files/6c72fcb9-efa3-447a-ab78-91812e39aee6.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: xqtann/ped#6

**Comment by yxtan02** [comment]
Specify that index should be <= 2147483647 (max int size)
Add known issues session for this issue
