### ISSUE TITLE
[PE-D][Tester E] UI issue after edit contact

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-3/tp#225]
First contact unexpectedly jumps away after editing the contact

<i><video controls><source src="https://raw.githubusercontent.com/xqtann/ped/main/files/68028849-3c03-46d1-b100-3368cc0a60b5.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/xqtann/ped/main/files/68028849-3c03-46d1-b100-3368cc0a60b5.mov</i>

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: xqtann/ped#10

**Comment by YangQF2002** [comment]
Fixed in #155
