### ISSUE TITLE
[PE-D][Tester A] Inappropriate Delete Error Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-3/tp#241]
![image.png](https://raw.githubusercontent.com/BuffWuff1712/ped/main/files/afca64e5-abba-4252-a502-0659cfcbf3a1.png)

Although the correct command is used (but wrong index number), the response in the output box mentions the above, even though it is a known command. Perhaps the team may want to adjust the error message.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: BuffWuff1712/ped#8

**Comment by YangQF2002** [comment]
Wrong command its supposed to be delete_<guest/vendor>
