### ISSUE TITLE
[PE-D][Tester A] Address field accepts forward slashes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-3/tp#242]
![image.png](https://raw.githubusercontent.com/BuffWuff1712/ped/main/files/96c659e8-3ed2-467a-a762-4334380ff497.png)

Assuming the address field is for property addresses, property addresses typically do not have forward slashes, but the add_guest/add_vendor commands allow the inclusion of such slashes

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: BuffWuff1712/ped#9

**Comment by slye20** [comment]
Add to planned enhancements
