### ISSUE TITLE
[PE-D][Tester C] Duplicate emails allowed when adding a new vendor

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-3/tp#252]
![image.png](https://raw.githubusercontent.com/jasmiinee/ped/main/files/bdd37a48-b8f5-45de-9ef0-b046d9e7f0b1.png)
Both vendor `John Doe` and `John Doee` have the same email

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jasmiinee/ped#19

**Comment by YangQF2002** [comment]
There exist a case where both vendors may have the same email (ie: same parent company) 
Hence, allowing duplicate emails is (arguably) okay :D
